controllers:
    resource: ../src/Controller/
    type: attribute

app_service_list:
    path: /
    controller: App\Controller\ServiceController::listAction

admin_service_list:
    path: /admin
    controller: App\Controller\AdminController::listAction

admin_service_new:
    path: /admin/service/new
    controller: App\Controller\AdminController::newAction

admin_service_edit:
    path: /admin/service/{id}/edit
    controller: App\Controller\AdminController::editAction

admin_service_delete:
    path: /admin/service/{id}/delete
    controller: App\Controller\AdminController::deleteAction
